parameters:
    memcache.doctrine_cache.class: Lsw\MemcacheBundle\Doctrine\Cache\MemcachedCache
    memcache.session_handler.class: Lsw\MemcacheBundle\Session\Storage\LockingSessionHandler
    memcache.default_options:
        compression: false
        serializer: php
        prefix_key: ""
        hash: default
        distribution: modula
        libketama_compatible: false
        buffer_writes: false
        binary_protocol: false
        no_block: false
        tcp_nodelay: false
        socket_send_size: ~
        socket_recv_size: ~
        connect_timeout: 1000
        retry_timeout: 0
        send_timeout: 0
        recv_timeout: 0
        poll_timeout: 1000
        cache_lookups: false
        server_failure_limit: 0

lsw_memcache:
    session:
        client: default
    clients:
        default:
            hosts: %memcachedhosts%
              
            options:
                compression: true
                serializer: 'json'
                prefix_key: ""
                hash: default
                distribution: 'consistent'
                libketama_compatible: true
                buffer_writes: true
                binary_protocol: true
                no_block: true
                tcp_nodelay: false
                socket_send_size: 4096
                socket_recv_size: 4096
                connect_timeout: 1000
                retry_timeout: 0
                send_timeout: 0
                recv_timeout: 0
                poll_timeout: 1000
                cache_lookups: false
                server_failure_limit: 0
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: default
            entity_manager: [default, read]  # you may specify multiple entity_managers
            prefix: "result_"                # you may specify a prefix for the entries
        query_cache:
            client: default
            entity_manager: default
        
