parameters:
    memcache.doctrine_cache.class: Lsw\MemcacheBundle\Doctrine\Cache\MemcachedCache
    memcache.session_handler.class: Lsw\MemcacheBundle\Session\Storage\LockingSessionHandler
    memcache.default_options:
        compression: false
        serializer: php
        prefix_key: ""
        hash: default
        distribution: modula
        libketama_compatible: false
        buffer_writes: false
        binary_protocol: false
        no_block: false
        tcp_nodelay: false
        socket_send_size: ~
        socket_recv_size: ~
        connect_timeout: 1000
        retry_timeout: 0
        send_timeout: 0
        recv_timeout: 0
        poll_timeout: 1000
        cache_lookups: false
        server_failure_limit: 0
