services:
    lsw.cache_invalidator:
        class: Lsw\MemcacheBundle\Cache\CacheInvalidator
        public: false
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments: [ @service_container ]

    lsw.full_page_cache:
        class: Lsw\MemcacheBundle\Cache\FullPageCache
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


